### ISSUE TITLE
Enhancement request: Optional background colour

### ISSUE THREAD

**Issue by Wargh** [tilfinltd/aws-extend-switch-roles#114]
It would be nice to be able to select a role based background colour so that I can, for example, set my prod accounts to red to add extra contrast to non-prod

**Comment by tilfin** [comment]
I changed it in V2 to work when the user presses the extension's button so as not to cause future security problems. This means that the content of the page displayed in the browser cannot be automatically altered when it is opened..

Hence, it is difficult to implement the desired function.
