### ISSUE TITLE
Hitting Chrome Sync limit...

### ISSUE THREAD

**Issue by TryTryAgain** [tilfinltd/aws-extend-switch-roles#123]
Is there any way to allow for local storage as an option, vs chrome sync only, for Chrome? Firefox version works perfectly fine, but with 200+ accounts and growing fast, I'd like to continue using Chrome but cannot as the config no longer saves because it's larger than the sync storage limit. Of course, if I wanted to add colors, regions, icons, etc this reaches the limit even sooner than 200 as referenced in other issues.

Existing issues: https://github.com/tilfin/aws-extend-switch-roles/issues/94 and https://github.com/tilfin/aws-extend-switch-roles/issues/52

**Comment by TryTryAgain** [comment]
I'm looking at this fork: https://github.com/snowplow-devops/aws-extend-switch-roles/commit/5d3ecf9820611589057a0755a2af08ba42a1d64e and it looks like it may attempt to solve this issue. I'm going to try it out. If it works, would you be willing to pull it up and commit to this project or use it as a starting point to consider offering the option to switch between local and sync storage?

**Comment by TryTryAgain** [comment]
Unfortunately, snowplow's commit also removed the functionality for the Config sender extension API which I rely on heavily. I tried to get it working but in the end, I simply resorted to changing out all occurrences of `chrome.sync` with `chrome.local` storage and all seems to be good and happy.

**Comment by tilfin** [comment]
Could you implement your Config Extender to switch the settings that each contain less than 200 accounts and to send it to AWS Extend Switch Roles?

**Comment by TryTryAgain** [comment]
To get your aws-extend-switch-roles to accept more than 200 profiles I changed all occurrences of `chrome.storage.sync` with `chrome.storage.local`. I also did use/add/replace with some of snowplows fork to support large file config but I did not remove.

For the config sender, I was using the https://github.com/netguru/sync-aws-extend-switch-roles Config sender example where all I did was switch out github -> gitlab. It did in fact work.

In my tests; using a small, our standard, and a large config all worked:
small.txt - 1.6k
roles.txt - 17k
large.txt - 42k

That works. I'm able to pass the equivalent of ~400 roles from a custom config sender to a custom aws extend switch role. That was awesome...but it does not work when publishing to the chrome web store and I have no idea why...

**Comment by TryTryAgain** [comment]
@tilfin I used the example the `netguru` example: https://github.com/netguru/sync-aws-extend-switch-roles and I didn't need to change anything with that project to support more than 200 (although my fork did change github -> gitlab).

What I did with your `aws-extend-switch-roles`, to get more than 200 profiles working, is I made almost all changes done by the snowplow fork to support large config file fix (almost all...I did not remove the lztext as they did, and I did not remove the config sender as they did, but I did swap out `profiles` -> `aws_profiles` bits and the `pages` part). And then I replaced all `chrome.sync` with `chrome.local` and changed the data_splitter warning from <200 to <2000 so it wouldn't complain. 

I've tested now successfully with over 600 accounts including image, region, color added to each profile. The config sender works, `aws-extend-switch-roles` works, and the profiles are all displayed and listed on the aws console page.

**Comment by TryTryAgain** [comment]
I have now discovered one issue with the setup I described above...

For some reason, guessing something in `load_aws_config` or somewhere else, is not fully working. Although the config sender sends to the modified aws extend switch role and the config is saved and displayed in the extension's options. While they also show up in the aws console webpages, and I can switch roles as expected, after testing with say 600+ accounts I noticed that although I get updates from remote configs via config sender if there are updates or I switch the link, on the aws console the role list doesn't get cleared (it gets updated, but it doesn't remove items that are no longer in the config; there are artifacts from previous configs being left on the bottom somehow)...I'm investigating that issue now.

**Comment by TryTryAgain** [comment]
I would also like to note, although the solution I provided above is working pretty great...I have discovered a small annoyance I have not been able to solve. I'm occasionally getting 404's where the URL should be https://console.aws.amazon.com ..... somehow/sometimes it's dropping console and redirecting to https://aws.amazon.com.... and I get a 404, but pressing the back button in the browser resolves the 404 and gets me into the account I'd originally intended to switch to before being met with the 404. It's a weird one, it seems very likely this happens more often when a resource doesn't exist in the target account and was selected in the current account and when role switching to the other account if the resource doesn't exist this may occur, but seems like it can all be solved if I knew why `console.` would be getting dropped when role switching.

**Comment by villeliskisolita** [comment]
Hi, I'm hitting the limit with Google Chrome 81.0.4044.113 and AWS Extend Switch Roles 0.14.0.
The exact limit seems to be 14653 bytes (characters with spaces)
Firefox plugin works perfectly. I will have to look for alternatives or some other methods to avoid hitting the limit any time soon.

**Comment by tilfin** [comment]
address this issue at #194

**Comment by TryTryAgain** [comment]
@tilfin it still hasn't been accepted and published by the Chrome Webstore Team? Very excited for its release. Thanks again!

**Comment by tilfin** [comment]
@TryTryAgain Yes, this status remains 'Waiting for review.'

**Comment by tilfin** [comment]
It's finally released.
