### ISSUE TITLE
In configuration [profile ]the character / is not accepted. No validation is performed

### ISSUE THREAD

**Issue by aleon1220** [tilfinltd/aws-extend-switch-roles#124]
I tried creating the following:
```
[profile deref-CI/CD]
role_arn = arn:aws:iam::1234325648:role/OrganizationAccountAccessRole
region   = ap-southeast-2
color    = 07d191
```

In AWS console it would never appear. 
is because of the character `/` there is no validation in place.

**Comment by deadlysyn** [comment]
If there isn't already WIP for this, I'd like to try figuring it out for Hacktoberfest. :-)

**Comment by deadlysyn** [comment]
Thinking aloud... In playing around with how the CLI handles profile names (resorted to that because I wasn't able to find a doc on allowed characters), it seems "/" is not an illegal character per se but this is perhaps about URL encoding.

**Comment by aleon1220** [comment]
> Thinking aloud... In playing around with how the CLI handles profile names (resorted to that because I wasn't able to find a doc on allowed characters), it seems "/" is not an illegal character per se but this is perhaps about URL encoding.

then there should be some notice or validation on how to name the AWS Profiles.

**Comment by tilfin** [comment]
If you enable `hide your account ID` option, it works with `/`.
It's set as a form input value, so it is encoded. It seems to be caused by something in the redirection process by AWS console.

**Comment by kiddom-kq** [comment]
I just got hit with a similar bug. Apparently the `#` character is also not supported inside of the `[profile ...]` sections.

E.G.:

```
[profile production-someUserRoleNameHere]
# A comment hear means that the plugin will silently fail to parse the config and you'll get no entries on the popup when clicking the plugin
role_arn = arn:aws:iam::123456789012:role/someUserRoleNameHere
source_profile = production
```

```
# But a comment here is fine. This entry will show up on the popup when the extension is activated/clicked.
[profile production-someUserRoleNameHere]
role_arn = arn:aws:iam::123456789012:role/someUserRoleNameHere
source_profile = production
```


It took a bit of trial and error to figure that out, but eventually found that any comment inside/under the `profile` heading will silently fail.

While a fix would be appreciated, emitting *any* user visible message that parsing failed would be enough

**Comment by tilfin** [comment]
I confirmed AESR works to switch the profile name that contains `/` regardless of `hide your account ID` at latest version.

**Comment by aleon1220** [comment]
Thanks, Everyone for the hard work
