### ISSUE TITLE
login federation support

### ISSUE THREAD

**Issue by hoshsadiq** [tilfinltd/aws-extend-switch-roles#136]
Currently using Okta to login, and when I use the extension to change account, it doesn't seem to work. I'm not sure if I've misconfigured or it just isn't supported.

**Comment by destornillador** [comment]
I am using Okta as SSO and I can jump between roles without any problem. My setup is something like this:

```
[AN AWS PROFILE]
role_arn = arn:aws:iam::1111111111:role/AdministratorAccess-Role
color = 003500
region = eu-central-1
```

Tested on Firefox 76 and using the release v0.14.0

**Comment by hoshsadiq** [comment]
Ah okay, have you set up any special IAM permissions for it to work? I'll have to check but it might be that our permission set hasn't been setup to AssumeRole across accounts. Thus it would only work from the main account.

**Comment by phancox** [comment]
I'm having issues when signed in via AWS SSO as nothing appears in the list.  If I sign into the same account with an IAM user everything works perfectly.  BTW thank you for a most useful extension.

**Comment by conork-datacom** [comment]
@phancox - Same deal for me, signing in via AWS SSO I just don't see any of the switchroles available...

**Comment by jpluscplusm** [comment]
+1: not seeing anything when logged in via AWS SSO. Happy to help debug this if anyone needs to see DOM contents when logged in in such a way.

**Comment by tilfin** [comment]
I have confirmed that AESR works to switch another account role after logging in both as an IAM user and via AWS SSO.

Is it possible to switch from ’Switch Roles’ link in the AWS MC menu without using AESR?

**Comment by krrrr38** [comment]
I use Azure AD with [saml2aws](https://github.com/Versent/saml2aws). At that time my aws config is like followings. Especially there is no `[source_from]` setting, but this is correct one.
```
[profile profile1]
role_arn = arn:aws:iam::111111111:role/some-role
source_profile = source_from # <- this profile doesn't exist in .aws/config. only exist in .aws/credential
region = ap-northeast-1
```

Currently aws-extend-switch-roles check `source_profile`. So if copy this settings to aws-extend-switch-roles configuration, no roles shown on the popup.
Workaround is here, need to remove `source_profile` settings then set this into aws-extend-switch-roles configuration.

```
[profile profile1]
role_arn = arn:aws:iam::111111111:role/some-role
region = ap-northeast-1
```

If `ignore_source_profile` configuration is existed in aws-extend-switch-roles, it might be helpful.

**Comment by tilfin** [comment]
@krrrr38 The configuration doesn't exactly match .aws/config format. That explanation may not be very well.

**Comment by hoshsadiq** [comment]
> Is it possible to switch from ’Switch Roles’ link in the AWS MC menu without using AESR?

That's probably the issue. I assume for this to work each role must be allowed to switch role to the other ones, in other words, if I log in as roleA, and I want to switch to roleB, roleA must have iam access to switch to roleB. In our case this is not possible, and it's a pretty big issue if your dev account can switch role to e.g. prod account. So I've not been able to set this up. Perhaps in this case the right approach would be to allow prod to switch roles to other accounts.

I suppose the only way to get this to work in a meaningful way is for cache credentials and update the relevant tokens in cookies or wherever aws console stores it's identity information. This however seems out of scope for this extension.

**Comment by krrrr38** [comment]
No, this is correct settings.

In the following section, `~/aws/config` doesn't have `[saml]`, it's only exist in `~/.aws/credentials:`
In this case, after generating  `[saml]` profile in `~/.aws/credentials`, even if there is no `[saml]` setting in `~/.aws/config`, we can call awscli using `--profile roleIn2ndAwsAccount`.

https://github.com/Versent/saml2aws#advanced-configuration-multiple-aws-account-access-but-saml-authenticate-against-a-single-sso-aws-account

**Comment by tilfin** [comment]
@krrrr38 You cannot setup the AESR configuration by copying and pasting `~/.aws/config`.  
I've rewritten the explanation. https://github.com/tilfinltd/aws-extend-switch-roles/commit/bc18dbfb3f1be94148326d26a8c56c1aa48a6023

**Comment by heikkis** [comment]
I'm using 2019 launched AWS SSO service for centralised login to accounts. It uses "Federated login" via SAML in background. 

In AWS Console I can see:

Federated Login: AWSReservedSSO_MSPDevelopersAccess_sadfasdfasdfasd/asdfasdf.asdfasdfasd@asdff.ff
My Account 123456789012

Is there a way to have aws-extend-switch-roles plugin to show the account name also in this case for me?

**Comment by tilfin** [comment]
@heikkis  No, the AESR can't apply anything to the Management Console screen right after signing in.

**Comment by abjrcode** [comment]
My organization is using AWS SSO with the SSO portal so I guess role switching won't work?
When I sign in to any account using the portal, I end up with a role named `AWSReservedSSOblabla` which I cannot switch to using the management console. To login in to a different account I always have to go to the portal.

From my understanding, AWS SSO deploys identity providers in each of the managed accounts. The user signs in once and 'somehow' he is trusted to login to the any accounts and assume his provided roles there without supplying their credentials again.

It seems that the individual identity providers in each account are linked somehow to a central one which authenticates the user once and gives them a session that can be used to login to the individual accounts.

Is this setup supported @tilfin ?

Cheers.

**Comment by tilfin** [comment]
@abjrcode Can you switch from ’Switch Roles’ link in the AWS Manage Console menu without using AESR? There is no function to shortcut switching between login destinations by AWS SSO.

**Comment by abjrcode** [comment]
@tilfin I couldn't manage to do that. I assume to get that working you would need a `root` account of some sort which you login in to then use it to assume roles in other accounts.
I was wondering how does the AWS SSO portal works under the hood to give you the ability to switch accounts and if that same mechanism can by utilized with AESR but I guess probably not?

**Comment by tilfin** [comment]
If you keep the browser tab that displays the AWS SSO portal open, it will serve the purpose.

**Comment by hoshsadiq** [comment]
Is it worth closing this issue considering this is out of scope for this extension? Feels like it might be worth adding some documentation but outside that, I don't see a need for this to be kept open.

**Comment by tilfin** [comment]
@hoshsadiq you'are right. I updated README.

**Comment by heikkis** [comment]
@tilfin now after federated AWS SSO login you can see in mouse hover the account alias name (sometimes, very strange) and if not, then always the account number as last parameter of the string.

Like rolename_username/asdf @ account-alias or account number. Could these be now used with the plugin?
