### ISSUE TITLE
Seem to reach a max config size, where config is not saved anymore

### ISSUE THREAD

**Issue by jalbstmeijer** [tilfinltd/aws-extend-switch-roles#145]
Hi,

Using aws-extend-switch-roles on Chrome 83.0.4103.61 on Linux.

After adding profiles beyond 37 saving stops working.
Not sure if it is the amount of proles, lines or characters that hit a max.

profiles: 37
lines: 293
characters: 8641

I do not get any error, just no "Configuration has been updated!" after hitting the save button and changes are lost.

Gr, J

**Comment by martinusnel** [comment]
Also seeing this, although with slightly different numbers.
AWS Extend Switch Roles version: `0.15.0`
Chrome version: Version 81.0.4044.129 (Official Build) (64-bit)
OS: `Linux`
Profiles: Somewhere after 125 and before 169 it breaks. Here is `wc` output from:
Working: `625    1250   18050`
Broken: `845    1690   24228`
Error: None. Just no `Configuration has been updated!` message and it does not update.

**Comment by tilfin** [comment]
address this issue at #194
