### ISSUE TITLE
In firefox the extension does not use the color for the entry if the image is also set

### ISSUE THREAD

**Issue by ghost** [tilfinltd/aws-extend-switch-roles#149]
Hi,

I have defined the image and the color to the account entry, like:

[!!! XXX root-prod !!!]
color = ff2600
region = eu-west-1
aws_account_id = XXX
image = "https://www.xxx.xxx/cs/vrweb/images/icon_57x57.png"

It would seem that the color entry is entirely ignored, despite the fact the documentation states that the color and image entries are not mutually exclusive.

I think this is a bug, I was able to get (at one time) extension to show image and also colored text for the account in the dropdown, but I don't know now what I did to make the extension to skip the colors.. it might be that as I few around 10 or so account entries defined, and each are using the same image it starts to take some resources in the extension itself to skip the colors?

Arsi

**Comment by tilfin** [comment]
This issue was fixed at V2.
https://github.com/tilfinltd/aws-extend-switch-roles/blob/d966d1480c2143cb55f01c9ff2076ab671c12de1/src/popup.js#L141 ~143
