### ISSUE TITLE
Multiple scrollbars when using many accounts

### ISSUE THREAD

**Issue by fleaz** [tilfinltd/aws-extend-switch-roles#180]
Hey,

first of all, a massive thank you to all the people who made this extension. It's an absolute life saver if you use the AWS console seriously!

I currently use the plugin with 19 accounts, and when I open the extension I have two vertical scrollbars. One in the account list and one in the plugin popup itself. See the following screenshot:

![Screenshot_2020-10-08_09:45:41](https://user-images.githubusercontent.com/2489598/95430521-281bb100-094c-11eb-9a9e-b6f607372e28.png)
(Chromium 84, Plugin Version 2.0.5, Arch Linux, 4K Screen, 1.0x scaling)

I fiddled around a bit in the developer console and came up with a fix  by giving the outer `div` of the plugin a height of 100% so it fits inside the popup and then I used column flexbox for the `main` element (containing the search box and the account list) so they split up the available vertical space. This way the right scrollbar is gone and you only have the one on the left for the account list which is imho the best way to support long account lists. See the following screenshots for my fix and how the result looks:
![Screenshot_2020-10-08_09:59:40](https://user-images.githubusercontent.com/2489598/95431695-e55ad880-094d-11eb-9b3a-ad79a156377f.png)
![Screenshot_2020-10-08_10:10:20](https://user-images.githubusercontent.com/2489598/95432217-a7aa7f80-094e-11eb-8935-34943e3b167e.png)

I'm far away from being a web designer, so I don't know if the changes I made have any unwanted side effects or break in other scenarios. But if this looks sane I can give it a shot and submit a proper PR.

Best,
Felix

**Comment by fleaz** [comment]
Hey,
for some reasons I still have this issue. The behavirous of the scrollbars didn't changed with 2.0.6 and also now with 2.1, I get the same view as in the screenshot in my first post. Sorry for reporting this so late :/

**Comment by tilfin** [comment]
The roles list HTML and the stylesheets have been changed since v2.0.6. It may be that the font size is affected by the screen scaling, causing the problem.
