### ISSUE TITLE
Clicking addon icon twice produce an empty profiles list

### ISSUE THREAD

**Issue by Porkepix** [tilfinltd/aws-extend-switch-roles#183]
Running latest stable Firefox, when clicking one time tha addon icon (the key), it correctly displays the profile list.
Clicking it a second time leads to have an empty list. The list stays empty for any further click, until the console tab is refreshed. This allows for the list to work again one time, then to go glitchy again after the second use.

**Comment by OlofHaglund** [comment]
I have the same issue on firefox 82.0.2 (64-bit) running on Windows 10.

**Comment by tilfin** [comment]
Does this issue still happen with the latest v2.0.6 ?

**Comment by Porkepix** [comment]
Nope, seems it's fixed, thanks!
