### ISSUE TITLE
Saving a config with 197 profiles yields "QUOTA_BYTES_PER_ITEM quota exceeded"

### ISSUE THREAD

**Issue by Jacob-Doetsch** [tilfinltd/aws-extend-switch-roles#184]
**Version:**
2.0.5

**Steps to reproduce:**
Attempt to save a profile with 197 entries where each entry has a source_profile and each entry specifies a role_arn
![image](https://user-images.githubusercontent.com/15638167/98858469-bd570d00-2404-11eb-863e-9ca9141f76c5.png)

**Other notes:**
The config I tested with was 23711 characters/bytes

**Comment by richardcloudsoft** [comment]
I've also observed this problem when updating my config with more roles. A config that was 17468 bytes was OK; a config of 19754 bytes was too big.

**Comment by rrkraft** [comment]
Same here. Is there a way to increase this limit or work around it?

**Comment by tilfin** [comment]
address this issue at #194
