### ISSUE TITLE
Modify always-visible UI header bar based on account ID alone

### ISSUE THREAD

**Issue by jpluscplusm** [tilfinltd/aws-extend-switch-roles#185]
Hi there - thanks for this extension :-)

I wonder if it'd be possible to document how I can configure AESR to achieve the following?

I'd like to visibly modify the console header bar to show me which AWS account I'm in.

Not based on which Role I've assumed (those are managed by AWS SSO, and have annoyingly arbitrary names), but just to change the header bar based on the only info I have access to, that's also consistent across multiple users: the account ID.

I'm not even looking to change role using the extension: just to be able to tell, at a glance, which AWS account I'm in. 

I can't seem to make that work, as this config doesn't *seem* to DO anything!

```
[foo]
aws_account_id = 123456789
color = abcdef
```

Am I doing something wrong, or is the intent of the extension solely to use those "base" account definitions as data sources from which to inform the larger list of inheritable Roles (the exact thing I'm /not/ trying to use the extension to manage)?

**Comment by tilfin** [comment]
I changed it in V2 to work when the user presses the extension's button so as not to cause future security problems. This means that the content of the page displayed in the browser cannot be automatically altered when it is opened..

Hence, it is not possible to implement the desired function.
