### ISSUE TITLE
Enhancement Request - hide clients names

### ISSUE THREAD

**Issue by dvir-levy** [tilfinltd/aws-extend-switch-roles#197]
Hi, 

I am working on several customers and wanted to ask if it is possible to add option to hide roles in some way. 
The reason is that I share my screen with customers and dont want them to see the whole list of other customers.

Thank you for the great tool ! 
Dvir.

**Comment by tilfin** [comment]
Where do you mean the role list? Is it the 5 roles history in the AWS Management Console?

**Comment by dvir-levy** [comment]
I mean when clicking on the chrome extension I can see the first 15 accounts in my list, their names and account number. 
It could be great to have option to hide them so my other clients will not be able to see them while using the screen share. 
For example: to set option to have only search box and finding only when pressing "enter" (not on the fly like now)

**Comment by tilfin** [comment]
I think it's a particular requirement.
Before sharing the screen, I think It's better to make your AWS MC switch roll history only those of the customer.

**Comment by tilfin** [comment]
I won't implement this feature because it's too niche.
