### ISSUE TITLE
Enhancement Request - folder/tree like structure for roles

### ISSUE THREAD

**Issue by joshthompson** [tilfinltd/aws-extend-switch-roles#198]
I work in a number of teams within my organisation, each team has roles for all our environments.

This means I have a long list of roles similar to this

Team 1 - Sandbox
Team 1 - Stage
Team 1 - Beta
Team 1 - Production
Team 2 - Sandbox
Team 2 - Stage
Team 2 - Beta
Team 2 - Production
...

Would it be possible to have an option to allow the title for the role to structure it into a tree like structure within the UI. It could be done by using a forward slash like it is a directory.

[Team 1/Stage]
...

This would be a huge quality of life improvement for me and several colleagues that run into the same issue I do.

Thank you

**Comment by tilfin** [comment]
I believe that it is faster to enter words in the filter box to narrow down the selection than to manipulate the tree with the mouse.
For example, inputting `1 st` will narrow it down to only 'Team 1 - Stage', `2 pr` will narrow it down to only 'Team 2 - Production'.

**Comment by joshthompson** [comment]
Ahh yes, I somehow have never spotted the filter.

I would reason though that as you already must use the mouse to open up the extension (at least in the chrome version), it would still be marginally easier to continue doing so - if the UI was a little cleaner with the tree that is.

But anyway, I will start using the filter now, thank you!
