### ISSUE TITLE
How to customize the keyboard shortcut to open the popup menu?

### ISSUE THREAD

**Issue by armancohan** [tilfinltd/aws-extend-switch-roles#200]
There seems to be no way to change the keyboard shortcut to open the popup menu.
The current [shortcut](https://github.com/tilfinltd/aws-extend-switch-roles/pull/176) (cmd+shift+,) clashes with the commonly used shortcut of increasing font size in many applications (e.g., in Google docs).
Ideally a uses should be able to customize this in the options.

**Comment by tilfin** [comment]
@armancohan you can edit it at `chrome://extensions/shortcuts`.
