### ISSUE TITLE
Extension works only once

### ISSUE THREAD

**Issue by tsunamaru** [tilfinltd/aws-extend-switch-roles#205]
Hi!

On latest Firefox 89, extension breaks immediately after first call, and shows "Failed to fetch user info from the AWS Management Console page" until you reload page.
That's what I see in console:
```
Uncaught ReferenceError: ConsoleNavService is not defined
    <anonymous> moz-extension://d42a4ab9-908f-402d-86d4-b94f8a1fe87b/js/attach_target.js:6
    <anonymous> moz-extension://d42a4ab9-908f-402d-86d4-b94f8a1fe87b/js/attach_target.js:23
attach_target.js:6:19
Uncaught ReferenceError: ConsoleNavService is not defined
    <anonymous> moz-extension://d42a4ab9-908f-402d-86d4-b94f8a1fe87b/js/attach_target.js:6
    <anonymous> moz-extension://d42a4ab9-908f-402d-86d4-b94f8a1fe87b/js/attach_target.js:23
attach_target.js:6:19
Uncaught ReferenceError: ConsoleNavService is not defined
    <anonymous> moz-extension://d42a4ab9-908f-402d-86d4-b94f8a1fe87b/js/attach_target.js:6
    <anonymous> moz-extension://d42a4ab9-908f-402d-86d4-b94f8a1fe87b/js/attach_target.js:23
attach_target.js:6:19
Uncaught ReferenceError: ConsoleNavService is not defined
    <anonymous> moz-extension://d42a4ab9-908f-402d-86d4-b94f8a1fe87b/js/attach_target.js:6
    <anonymous> moz-extension://d42a4ab9-908f-402d-86d4-b94f8a1fe87b/js/attach_target.js:23
attach_target.js:6:19
```

Video demonstration: https://youtu.be/SoJU6G6mYk8

**Comment by tilfin** [comment]
It seems to be happening only on the new EC2 dashboard.

**Comment by ColinHalter** [comment]
Hello,

On chrome, I'm seeing the same issue in any service (Not just EC2). Console is giving the following error:

`content.js:88 Blocked form submission to 'https://signin.aws.amazon.com/switchrole' because the form's frame is sandboxed and the 'allow-forms' permission is not set.
(anonymous) @ content.js:88`

Switching roles works once, but trying again will just do nothing.

**Comment by tilfin** [comment]
The cause has been identified.
New feature pages in the AWS Console have multiple iframes, and AESR sends the control message to not only main body but also a part of iframes.
