### ISSUE TITLE
Session timeout setting

### ISSUE THREAD

**Issue by brendan-sherrin** [tilfinltd/aws-extend-switch-roles#209]
Hi,
Just wondering if there was any way to increase the timeout for assuming the role.  The role I'm assuming has a timeout value of 12 hours but my sessions timeout within 1 hour.  What value is being requested by the addon and/or can this be increased?

https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html
"DurationSeconds"

    The duration, in seconds, of the role session. The value specified can can range from 900 seconds (15 minutes) up to the maximum session duration that is set for the role. The maximum session duration setting can have a value from 1 hour to 12 hours <snip> By default, the value is set to 3600 seconds. 

Cheers

**Comment by tilfin** [comment]
AESR does the same operation as when you click on a link of the Role History on the AWS Management Console page and does not use the AWS API.
