### ISSUE TITLE
Enhancement Request - Dark Mode

### ISSUE THREAD

**Issue by snietzsche** [tilfinltd/aws-extend-switch-roles#210]
Many users use extensions like Darkreader when working in dark rooms to avoid eyestrain. When opening the AWS Extend Switch Roles extension, it's bright white background creates a jarring and uncomfortable experience. Two possible implementations (equally acceptable):

1. Add a dark-mode option, toggle-able in the Configuration menu as a check box.
2. Add a theme option with light and dark modes, selectable from a drop-down option in the Configuration menu.

Thanks for all the hard work on this extension. It's a huge lifesaver!

**Comment by tilfin** [comment]
released at v3.0.0
