### ISSUE TITLE
After upgrading to Firefox 93, roles no longer load

### ISSUE THREAD

**Issue by samuelturnerffrees** [tilfinltd/aws-extend-switch-roles#222]
I've replicated this issue on two computers running Kubuntu 20.04 LTS. After updating Firefox to version 93, my roles no longer load in the list when I click the plugin icon. I've double checked I'm using V2.2.0 of the plugin.

![image](https://user-images.githubusercontent.com/9381468/137892298-ccc944da-7acc-46cb-b6f4-75a5ca8f5943.png)

**Comment by viktorium** [comment]
I've noticed this happening when I log into the AWS console with the account number through https://console.aws.amazon.com. When I log in with the symbolic name the Role List works fine, e.g. https://my-aws-account.signin.aws.amazon.com/console.

**Comment by samuelturnerffrees** [comment]
This issue fixed itself after several days, no idea what changed and can no longer help debug, so closing this.
