### ISSUE TITLE
New AWS interface 18th Nov 2021

### ISSUE THREAD

**Issue by syquus** [tilfinltd/aws-extend-switch-roles#224]
Hello community,

I just saw a new interface, with major (at least visually) changes, and... as expected, my beloved aws-extend-switch-roles isn't working.

No errors at all. I just try to clic on the extension icon, then select another profile... and nothing happens.

Taking a look on the JS console, I can see:

On view-source:moz-extension://15c38e2c-d6a8-4109-8370-0c3debe72874/js/attach_target.js

`(function () {
  const elById = id => document.getElementById(id);
  const trimTxtCtn = el => el ? el.textContent.trim() : '';

  const info = {};
  const accInfo = ConsoleNavService.AccountInfo;
  if (accInfo) {
    Object.assign(info, accInfo);
    info.isGlobal = document.querySelector('#menu--regions li a') == null;
  } else {
    Object.assign(info, {
      loginDisplayNameAccount: trimTxtCtn(elById('awsc-login-display-name-account')),
      loginDisplayNameUser: trimTxtCtn(elById('awsc-login-display-name-user')),
      roleDisplayNameAccount: trimTxtCtn(elById('awsc-role-display-name-account')),
      roleDisplayNameUser: trimTxtCtn(elById('awsc-role-display-name-user')),
      isGlobal: document.querySelector('#regionMenuContent a') == null,
    })
  }

  elById('AESR_info').dataset.content = JSON.stringify(info);

  elById('AESR_form').csrf.value = AWSC.Auth.getMbtc();
})();
`

and that's it.
New interface snapshot here: https://gcdn.pbrd.co/images/A4jXL126SKKG.png?o=1
If there is anything I can do to help adapting the extension to this AWS, just let me know...

**Comment by gitclaranetes** [comment]
+1

**Comment by ikkaro** [comment]
Same issue here!

**Comment by vishksaj** [comment]
+1

**Comment by steven-aerts** [comment]
A temporary workaround is to first go to the [Support Center](https://console.aws.amazon.com/support/home?#/) where the old Console is still present and you can still switch to other accounts.

**Comment by stoltin** [comment]
+1

**Comment by tvb** [comment]
+1

**Comment by akshaykrjain** [comment]
+1

**Comment by jolvan** [comment]
+1

**Comment by loulbani** [comment]
+1

**Comment by WitoldSlawko** [comment]
+1

**Comment by ap-hyperbole** [comment]
+1

**Comment by SammyHerring** [comment]
+1

**Comment by dr00min** [comment]
Same here, major customer infrastructures are affected.

**Comment by anthoc** [comment]
+1

**Comment by tilfin** [comment]
I'm working on this issue. I would appreciate it if you could sponsor me because I would lose my regular work time.

**Comment by Ian-T-Price** [comment]
> 6 sponsors are funding tilfinltd’s work.
> 
> @tilfinltd
> @tilfinltd's goal is to have 200 sponsors
> We're sure there are numerous companies and teams using AWS Extend Switch Roles as they have over 60,000 users.

Individual sponsorship at $1 pm would be  good idea to increase support

**Comment by niknkson** [comment]
+1

**Comment by Ian-T-Price** [comment]
You might want to hang fire on any changes.  It appears that AWS has rolled back the changes...

**Comment by timschill** [comment]
> > 6 sponsors are funding tilfinltd’s work.
> > @tilfinltd
> > @tilfinltd's goal is to have 200 sponsors
> > We're sure there are numerous companies and teams using AWS Extend Switch Roles as they have over 60,000 users.
> 
> Individual sponsorship at $1 pm would be good idea to increase support

I would not mind paying a monthly or yearly fee for a piece o software that makes my daily work so much more efficient.

**Comment by niknkson** [comment]
@Ian-T-Price  Looks like again they push the changes and aws-extend-switch-role stop working.

**Comment by Ian-T-Price** [comment]
I've spotted the difference; the changes are in EU-West-1 but not EU-West-2, Yet... Another temporary work around; find the region that hasn't had it applied!

**Comment by nickhudkins** [comment]
Just want to call attention to my comment here: https://github.com/tilfinltd/aws-extend-switch-roles/pull/225#discussion_r753237562 which should be considered for anyone working on a fix for this, since deploys will take time to roll across all regions, you'll be chasing a fix, and this will allow the selector to remain slightly more resilient to this difference.

**Comment by nickhudkins** [comment]
Further bit of information, the change that resulted in the extension working in some regions and not in others is being reverted, so the extension should return working with no further code changes shortly.

**Comment by tvb** [comment]
> I'm working on this issue. I would appreciate it if you could sponsor me because I would lose my regular work time.

I would like to know how my company could sponsor you?

**Comment by tilfin** [comment]
AWS side patched all the regions and returned it.

**Comment by maslick** [comment]
seems to be working now ;)

**Comment by quapaw** [comment]
This is not working for me in Chrome.  Any pointers

**Comment by tilfin** [comment]
There is a separate issue where some of the service pages do not work with the new UI, so please try the AWS Management Console top page.

**Comment by tilfin** [comment]
added one-time tier in https://github.com/sponsors/tilfinltd 🙇
