### ISSUE TITLE
Broken images/background color

### ISSUE THREAD

**Issue by nickjmv** [tilfinltd/aws-extend-switch-roles#238]
Hi,

Since the last update, I've been experiencing issues with layout when adding a color AND a picture.

The color is present behind the image which makes it ugly. Also when removing the color from the config, a grey background is displayed behind the image.

Is this expected behaviour now or is this something that broke in the last release? Because before it was displaying only the image without color background.

**Comment by nickjmv** [comment]
Ah okay, so right now this is how it was meant to be?

Then this can be closed, I'll modify my images ;)

**Comment by tilfin** [comment]
I'll fix not to apply gray to the background if the color is undefined. If a color is specified, apply it as is.

**Comment by nickjmv** [comment]
Ah that would be very cool of you!

**Comment by tilfin** [comment]
released v2.3.1
