### ISSUE TITLE
Invalid information in one or more fields

### ISSUE THREAD

**Issue by georg-ikegps** [tilfinltd/aws-extend-switch-roles#247]
I would like to use this extension in an SSO/Control Tower setup.

I've read that in this case I should first login into the main account and switch roles from there?
If that or if I login into the account directly - I always get this message:
`Invalid information in one or more fields. Check your information or contact your administrator.`

Is there anything specific to setup for this scenario?

**Comment by georg-ikegps** [comment]
my bad ... I confused matters.
When I use a role that I can actually assume it works.
I had thought that it allows me to switch between roles that are defined via SSO ... but I first need to set it up.

**Comment by tilfin** [comment]
It is not possible to switch directly to a target role from the list on the SSO page.
