### ISSUE TITLE
QuotaExceededError: storage.sync API call exceeded its quota limitations.

### ISSUE THREAD

**Issue by nitrocode** [tilfinltd/aws-extend-switch-roles#248]
Thank you for an extremely useful extension. I've recommended this to many happy users.

I see this in Firefox with 169 profiles.

```
QuotaExceededError: storage.sync API call exceeded its quota limitations.
```

If I reduce it to 156 profiles, my configuration is saved successfully.

```
Configuration has been updated!
```

Edit: nevermind, I'm told I can avoid this by using local storage. Seen in https://github.com/tilfinltd/aws-extend-switch-roles/issues/242#issuecomment-1022948597.

**Comment by tilfin** [comment]
The profile number limit for Sync storage is 200, but it depends on the text length of the configuation and may exceed the storage size if it is long.
