### ISSUE TITLE
Limit on number of accounts to be loaded in configuration

### ISSUE THREAD

**Issue by mdevicariis-sf** [tilfinltd/aws-extend-switch-roles#249]
When I add all of our account ( >30 accounts ), it only loads the last X (19?) accounts. If the max number is exceeded, the first ones loaded from the config are unaccessible.

* What is the limit?
* Can we raise the limit?

As a workaround, I have to use 2 browsers with local configs. One browser for GovCloud accounts & another browser for Com accounts.

**Comment by tilfin** [comment]
If the limit is exceeded, saving your configuration should fail at first. The limit is the maximum number of profiles or the maximum text length of the configuration. Changing from Sync Storage to Local Storage will raise the limit.

**Comment by mdevicariis-sf** [comment]
My config is set on local storage.

What's the limit on profiles? That's what I'm finding here. I'm exceeding the number of profiles and the older profiles are pushed out. Can we raise the max number of profiles?

**Comment by tilfin** [comment]
What browser do you use?
Chrome’s local storage should be able to register at least 100 profiles, or do you have a lot of comments in your configuration?

**Comment by mdevicariis-sf** [comment]
I prefer to use Chrome. Firefox is my alternate.

I have 38 profiles, well under the 100 you say can be registered.

Below is the list of profiles that I have.
`
% grep '\[' aws-switch-role-extension-config-devops-combined.ini
[2f-master-gov]
[2f-master-com]
[2f-master-gov]
[2f-il2-sandbox-gov]
[2f-il2-cloudops-gov]
[2f-il2-networking-gov]
[2f-il2-logging-gov]
[2f-il2-dev-gov]
[2f-il2-test-gov]
[2f-il2-staging-gov]
[2f-il2-prod-gov]
[2f-il2-data-gov]
[2f-il4-cloudops-gov]
[2f-il4-logging-gov]
[2f-il4-sraging-gov]
[2f-il4-prod-gov]
[2f-il5-cloudops-gov]
[2f-il5-logging-gov]
[2f-il5-staging-gov]
[2f-il5-prod-gov]
[2f-il2-sandbox-com]
[2f-il2-master-com]
[2f-il2-cloudops-com]
[2f-il2-networking-com]
[2f-il2-logging-com]
[2f-il2-dev-com]
[2f-il2-test-com]
[2f-il2-staging-com]
[2f-il2-prod-com]
[2f-il2-data-com]
[2f-il4-cloudops-com]
[2f-il4-logging-com]
[2f-il4-staging-com]
[2f-il4-prod-com]
[2f-il5-cloudops-com]
[2f-il5-logging-com]
[2f-il5-staging-com]
[2f-il5-prod-com]
`
Attached is a screenshot of my list, showing only COM profiles.
![Screen Shot 2022-04-15 at 08 14 44](https://user-images.githubusercontent.com/81390278/163588390-4fd3ba00-1935-42a4-b040-2b0bc246a065.png)

**Comment by mdevicariis-sf** [comment]
Is it possible the conflict is that both gov and com master accounts have the same account alias?

> ;;;;;;;;;;;;;;;;;;;;;;
> ;;  Master Accounts ;;
> ;;;;;;;;;;;;;;;;;;;;;;
> 
> [2f-master-gov]
> aws_account_id = 2f-master
> 
> [2f-master-com]
> aws_account_id = 2f-master

**Comment by tilfin** [comment]
That is the cause. The profiles associated with the base account overwritten will not be displayed.

**Comment by mdevicariis-sf** [comment]
Do I have to use the account alias or can I use the account number so they won't overwrite?

**Comment by tilfin** [comment]
This type of use was not expected so it cannot be handled currently. It would be nice if you could separate gov and com by account number, but that would require a change in the organization's settings. The only way to do this is to separate the profile configs for each Chrome account for gov and com.

**Comment by mdevicariis-sf** [comment]
My coworker found a way to make it work without using org profiles. We simply use the target account alias as the aws_account_id, then specify the role_name. This is working for both of us.

**Comment by Burekasim** [comment]
Hi, 

We encounter a similar solution, we have over 190 roles (and it's keep growing) and we receive the error: 
![image](https://user-images.githubusercontent.com/37156629/173230488-f3c443ce-500e-4047-a863-030cfb337966.png)

QUOTA_BYTES_PER_ITEM quota exceeded. is there a local fix that can be applied?

**Comment by tilfin** [comment]
The number of profiles that can be registered has been increased in v4.0.0.
While this removes any fixed upper limit on the number of profiles, there will now be a restriction based on the text size of the Configuration.
