### ISSUE TITLE
Is it possible to use this extension with AWS SSO and permission sets?

### ISSUE THREAD

**Issue by rayterrill** [tilfinltd/aws-extend-switch-roles#250]
Seeing some conflicting info in docs and issues, finding it hard to understand. Happy to help add docs if this is supported and just unclear.

We have AWS SSO set up in a root account auth'ing to Okta, and then various permissions sets in other accounts. The OOTB AWS SSO switcher is fine to use as a tab you just keep open, but we use this extension heavily and would love to use this as well if it's possible with this configuration.

Cheers.

**Comment by tilfin** [comment]
If you mean to replace the yellow link in the screenshot below, AESR cannot do that.
![aws-sso-home](https://user-images.githubusercontent.com/519017/164888495-903b11f3-b382-4d94-bb73-33b9dc3e5eda.jpg)

Sure, it is slow until the management console opens, but I think this is a necessary process that cannot be shortened.

**Comment by rayterrill** [comment]
I thought that was the case, just wanted to confirm. Thanks @tilfin
