### ISSUE TITLE
Show only matching roles ignores IAM roles with paths

### ISSUE THREAD

**Issue by dliao-tyro** [tilfinltd/aws-extend-switch-roles#258]
We recently tried to use the extension for IAM roles with path prefixes:

```
[identity]
aws_account_id = xxx-identity

[DEV-DevAdmin]
aws_account_id = development
role_name = human/WorkflowDevAdmin
source_profile = identity
color = 2384fd
```

With the "Show only matching roles" option enabled, that role isn't available via the extension anymore.

**Comment by tilfin** [comment]
It should not be possible to include '/' in the role_name of the switch target.

Try the following:
```
[identity]
aws_account_id = xxx-identity
role_name = human

[DEV-DevAdmin]
aws_account_id = development
role_name = WorkflowDevAdmin
source_profile = identity
color = 2384fd
```
With the "Show only matching roles" option **disabled**
