### ISSUE TITLE
csp issue with switchrole link

### ISSUE THREAD

**Issue by N426ER** [tilfinltd/aws-extend-switch-roles#260]
When clicking on a role to switch to, the extension silently fails to respond. An inspection of the console shows there is a csp issue preventing the action:

- error: `Refused to send form data to '[https://signin.aws.amazon.com/switchrole'](https://signin.aws.amazon.com/switchrole%27) because it violates the following Content Security Policy directive: "form-action 'none'".`
- version: `2.3.1`
- chrome: `Version 104.0.5112.101 (Official Build) (arm64).`
- Also tried re-installing the extension and used a fresh incognito session with the same error.

Worth noting, there is a support post on the Chrome web store that demonstrates a similar issue with a different error message:

- `/systems-manager/home?region=us-east-1#:1 Refused to send form data to 'https://signin.aws.amazon.com/switchrole' because it violates the following Content Security Policy directive: "form-action https://us-east-1.signin.aws.a".`

**Comment by tilfin** [comment]
This is because the AWS Management Console temporarily returns an incorrect CSP. With the Content Security Policy (form-action 'none'), the switch role history links in the AWS MC page would not work either. In any case, it cannot be handled by the extension.
