### ISSUE TITLE
Allow switching when using the LightSail service

### ISSUE THREAD

**Issue by daltschu22** [tilfinltd/aws-extend-switch-roles#264]
It seems when using the LightSail service that role switching is not allowed. 

Error message is "Failed to fetch user info from the AWS Management Console page"

I assume this is because the LightSail console is not within the normal AWS console. Is it possible to modify to allow switching from Lightsail?

Thanks!

**Comment by tilfin** [comment]
AESR supports LightSail page at v2.3.2.
