### ISSUE TITLE
Q: When to use [profile name] and when to use [name]

### ISSUE THREAD

**Issue by cytopia** [tilfinltd/aws-extend-switch-roles#269]
I still didn't manage to figure out the difference between using the `profile` prefix and when to omit it.

What is the difference between (with `profile`):
```ini
[profile some-name]
role_arn = arn:aws:iam::123456789:role/ROLE1
region = eu-central-1
color = 99e699
```
and this one (without `profile`)
```ini
[some-name]
role_arn = arn:aws:iam::123456789:role/ROLE1
region = eu-central-1
color = 99e699
```

**Comment by tilfin** [comment]
There is no difference. However, it is better not to write `profile ` because it reduces the amount of configuration text.

**Comment by cytopia** [comment]
Alright, thanks!
