### ISSUE TITLE
Please let us add more than 200 profiles

### ISSUE THREAD

**Issue by kjedamzik** [tilfinltd/aws-extend-switch-roles#270]
>  **Failed to save bacause the number of profiles exceeded maximum 200!** 

Thank you for this awesome plugin in, but could you please remove the limit of 200 profiles or make the number configurable, as the number of profiles I want to add exceeds 200.

**Comment by tilfin** [comment]
Please select `Local` as **Configuration storage**. 
https://github.com/tilfinltd/aws-extend-switch-roles/tree/v2.3.2#settings

**Comment by tilfin** [comment]
The number of profiles that can be registered has been increased in v4.0.0.
