### ISSUE TITLE
Failed to fetch user info from the AWS Management Console page

### ISSUE THREAD

**Issue by 74Rog** [tilfinltd/aws-extend-switch-roles#277]
I got a pop-up saying role was disabled as per issue #276 

I re-enabled granting the additional permissions and now it doesn't work.
I get the following message; Failed to fetch user info from the AWS Management Console page
How can I fix this?

![image](https://user-images.githubusercontent.com/36132650/203072211-37c97248-24e8-407b-a076-7b167bb374a1.png)

**Comment by tilfin** [comment]
Please tell me the URL (domain) of the browser tab when you shew the pop-up.

**Comment by atom888888** [comment]
I am getting this same error message?  I'm not sure why it's broken, what happened and how I can fix it?

This is the URL I'm at when I get the error message:
https://us-east-1.console.aws.amazon.com/iamv2/home?region=us-east-1#/home

**Comment by atom888888** [comment]
> I am getting this same error message? I'm not sure why it's broken, what happened and how I can fix it?
> 
> This is the URL I'm at when I get the error message: https://us-east-1.console.aws.amazon.com/iamv2/home?region=us-east-1#/home

I am getting this same error message? I'm not sure why it's broken, what happened and how I can fix it?

This is the URL I'm at when I get the error message:
https://us-east-1.console.aws.amazon.com/iamv2/home?region=us-east-1#/home

**Comment by atom888888** [comment]
> Please tell me the URL (domain) of the browser tab when you displayed the pop-up.

I am getting this same error message? I'm not sure why it's broken, what happened and how I can fix it?

This is the URL I'm at when I get the error message:
https://us-east-1.console.aws.amazon.com/iamv2/home?region=us-east-1#/home

**Comment by tilfin** [comment]
merged #246
