### ISSUE TITLE
Assumable Roles not showing up within AWS China Account

### ISSUE THREAD

**Issue by Asgaros** [tilfinltd/aws-extend-switch-roles#283]
No assumable roles show up when I am in the organization root account running within AWS China.

If I define the organization root account only within the configuration, then it shows up properly:

```
[org1]
aws_account_id = 000011112222
```
![image](https://user-images.githubusercontent.com/12525671/229670471-25fd4740-3e95-4aca-be9f-1d6d7ade2229.png)

As soon as I add a sub-account and link it to the organization, nothing is shown anymore:

```
[org1]
aws_account_id = 000011112222

[org1account1]
role_arn = arn:aws-cn:iam::123456789012:role/OrganizationAccountAccessRole
source_profile = org1
region = cn-northwest-1
```

![image](https://user-images.githubusercontent.com/12525671/229670700-219cb1e8-2151-4b54-8f84-0daf7c0de550.png)

**Environment**
 - OS: Windows 11
 - Browser: Edge
 - Browser Version: 111.0.1661.62 (64-Bit)
 - Extension Version: 2.3.2

**Comment by oilegor1029** [comment]
I have the same problem in Safari and Brave
OS: MacOS 13.3.1 (a) Ventura

**Comment by oilegor1029** [comment]
Fix: https://github.com/tilfinltd/aws-extend-switch-roles/issues/208#issuecomment-904134424

**Comment by Asgaros** [comment]
@oilegor1029 

Good catch! I had to define the Account ID and the Account Alias. Since I am logging into the account with the Account Alias, it was not showing up without defining it in the configuration. It would be great, if it would work without the need to define the other.

Anyway, I will close this issue since it is not really related to the issue initially described.

Thanks!
