### ISSUE TITLE
Plugin fails to be added to toolbar in Firefox Developer Edition

### ISSUE THREAD

**Issue by piersatdoshii** [tilfinltd/aws-extend-switch-roles#291]
When using this plugin with Firefox Developer Edition, although it appears to install fine (and can access its settings via the Addons screen), it fails to add itself to the toolbar (even when trying to customise toolbar).

Steps:
Install Firefox Developer Edition
Install AWS Extend Switch Roles addon

Expected:
Blue key icon for AWS Extend Switch Roles plugin visible on toolbar

Actual:
No change to toolbar

**Comment by XargsUK** [comment]
Hi @piersatdoshii. To try to replicate the issue, I've installed Firefox Developer Edition and followed the following steps: 

- Searched AWS Extend Switch Roles in the Firefox Add-On store and installed. 
- In the top right, clicked the Jigsaw icon (extensions), and clicked the cog icon next to AWS Extend Switch Roles, followed by Manage Extension. This will open `about:addon`
- In the `about:addon` page, went to **Permissions** and then toggled the sites which I want to grant access for. 
- In the top right, clicked the Jigsaw icon again, right click on AWS Extend Switch Roles, and click Pin to Toolbar. 

This worked as expected.

![Firefox Developer with extension installed](https://github.com/tilfinltd/aws-extend-switch-roles/assets/51077147/ccf29c49-b82c-4f70-a400-e8e358365a84)

**Comment by piersatdoshii** [comment]
Hi, manually adding those permissions worked for me, thanks!

**Comment by XargsUK** [comment]
@tilfin please could you mark as closed <3
