### ISSUE TITLE
Cannot See Target Roles when Logged into AWS via SSO (Identity Center)

### ISSUE THREAD

**Issue by ismail44** [tilfinltd/aws-extend-switch-roles#299]
**Describe the bug**
Cannot see "target roles" when logged into "base role" using AWS SSO.

**To Reproduce**
1. Update config with a base account that is an AWS SSO Permission Set
2. Log into AWS using SSO and that permission set in the base account
3. Click plugin to see roles that can be assumed

```
[base1]
aws_account_id = XXXXXXXXXXXXXX
role_name = some_role
[base2-sso]
aws_account_id = XXXXXXXXXXXX
role_name = some_permission_set
[base2-assumeable-role]
source_profile = base2-sso
role_arn = arn:aws:iam::XXXXXXXXXX:role/some_assumeable_role
```

**Expected behavior**
I would expect that by logging into the role identified by base2-sso, I would see base2-assumeable-role in my dropdown. 

**Environment**
 - OS: [MacOS]
 - Browser [chrome]
 - Version [115.0.5790.114 ]

**Comment by tilfin** [comment]
How is the Settings check list set up? Uncheck them all and try it.

Does your username start with `AWSReservedSSO_` after logging into AWS MC?

**Comment by ismail44** [comment]
Thanks for the reply.

All boxes are unchecked... and the permission set I choose is:

AWSReservedSSO_(rolename)_ca8fexxxxxxxx/{my email}

**Comment by tilfin** [comment]
@ismail44 Just to confirm, is the `_` included in the `ca8fexxxxxxxxxx` ? If so, it may cause this problem.

**Comment by tilfin** [comment]
If account alias is set as shown below, you must also define aws_account_alias.

<img src="https://github.com/tilfinltd/aws-extend-switch-roles/assets/519017/4a6ca228-b477-4614-b05f-bb02dc21cec5" width="40%">

```ini
[base-sso]
aws_account_id = 000011112222
aws_account_alias = company
role_name = some_permission_set
```

**Comment by ismail44** [comment]
That worked like a charm!!! Thanks.
