### ISSUE TITLE
Support of Firefox ESR

### ISSUE THREAD

**Issue by KrzysztofLesniczak** [tilfinltd/aws-extend-switch-roles#301]
**Is your feature request related to a problem? Please describe.**
Addon does not support ESR Version of Firefox. Extended Support Release is required in many cases in IT.
Manifest for firefox contains line:
`"strict_min_version": "109.0"`

ESR is in version 102.14.0esr

**Describe the solution you'd like**
Based on https://wiki.mozilla.org/index.php?title=Release_Management/Calendar&redirect=no
109.0 standalone, corresponds to 102.7 ESR so 102.14.0 ESR supports all features that are in 109 standalone.
Please change manifest to support ESR also

**Comment by tilfin** [comment]
Please download and install the previous version. The latest one is migrated to manifest V3, so supported Firefox min version could not be changed.
https://addons.mozilla.org/en-US/firefox/addon/aws-extend-switch-roles3/versions/
