### ISSUE TITLE
Add suport to Brave Browser

### ISSUE THREAD

**Issue by omata** [tilfinltd/aws-extend-switch-roles#302]
**Is your feature request related to a problem? Please describe.**
While this plugin works fine with the target browser, _(Google Chrome)_, it doesn't work with derivatives like Brave Browser.

**Describe the solution you'd like**
Add support to Brave Broser

**Describe alternatives you've considered**

**Comment by jacoor** [comment]
I am using it in brave for last 2 years at least..

**Comment by abnovak** [comment]
doesn't work for me either...

**Comment by tilfin** [comment]
I have confirmed that AESR works with Brave Browser on ｍy PC, so I can't do anything more without more information.

**Comment by omata** [comment]
Hello, it was my mistake, it just not synced all my identities, so I copy pared the configuration and it worked. Please close the issue
