### ISSUE TITLE
Roles are not diaplyed in Firefox private tabs

### ISSUE THREAD

**Issue by ysb33r** [tilfinltd/aws-extend-switch-roles#314]
**Describe the bug**
Since upgrading to 4.0, it seems the extension is not working in Firefox private tabs.
In my context there are a number of roles in different accounts that can be assumed. All these accounts are part  of an organisational account.

This seems to be related to #292, but I am creating a new issue as what is described in that issue is not quite the same.

**To Reproduce**
1. Open a private tab in firefox and sign-in to AWS.
2. Click the icon to get a list of roles.
3. No roles are displayed.

Close that private window and use a normal window to sign in. In this case all of the roles are displayed.

**Expected behaviors**
Private windows/tabs should heave the same as normal windows/tabs

**Environment**
 - OS: Fedora Linuz
 - Browser: Firefox
 - Version: 118.0

**Comment by tilfin** [comment]
It seems to be related to https://bugzilla.mozilla.org/show_bug.cgi?id=1841806 .

**Comment by rupe120** [comment]
> It seems to be related to https://bugzilla.mozilla.org/show_bug.cgi?id=1841806 .

Though according to that bug history, it was fixed in release 115. The OP is on 118 and I am using 119 and still see the issue.

**Comment by nhilo32** [comment]
What was the fix?

**Comment by rupe120** [comment]
@tilfin is there something I need to do to get my existing configuration stored into the fallback storage? I am still not seeing anything in private windows.

**Comment by tilfin** [comment]
In normal mode (non-private) browsing, open the configuration page and press the save button once.
