### ISSUE TITLE
Role assumption paths are truncated

### ISSUE THREAD

**Issue by tayopal** [tilfinltd/aws-extend-switch-roles#324]
**Describe the bug**
I have been using the plugin for 2 years with success. After the latest update, my coworkers and I have correctly-configured profiles that no longer work.

**To Reproduce**
1. Configure a pathed role as usual: 
```
[profile aws_one]
role_arn = arn:aws:iam::########:role/sso/path/to/rolename
color=441111
region=us-east-1
```
2. Load AWS console and attempt to switch roles
3. See the AWS switch role dialog with truncated role name: `sso`
<img width="522" alt="Screenshot 2023-11-06 at 10 55 55 AM" src="https://github.com/tilfinltd/aws-extend-switch-roles/assets/83922247/d8bb05b0-4ef6-4e09-9032-d48153cf19de">

**Expected behavior**
Successful role assumption.

**Environment**
 - OS: MacOS 14.0 (Sonoma)
 - Chrome 119
 - Plugin version 4.0.1

**Comment by tilfin** [comment]
That seems to be a bug. I will fix it.
