### ISSUE TITLE
First click in the extension icon opens empty role list

### ISSUE THREAD

**Issue by kstudzinski** [tilfinltd/aws-extend-switch-roles#330]
**Describe the bug**
The list of roles opens empty at the first attempt, and it opens normally on the second click. Happens to me on MacOS and on the other developer sitting next to me and having Windows.

**To Reproduce**
1. Login to AWS
2. Click icon
3. list is empty
![image](https://github.com/tilfinltd/aws-extend-switch-roles/assets/13691284/23c2eacf-9dc0-4f0b-931f-a0677d4716f9)
4. Click again
5. list is normal
![image](https://github.com/tilfinltd/aws-extend-switch-roles/assets/13691284/7d709f71-e7d3-4273-a470-ab240d90bbb1)
6. Works from now on

**Expected behavior**
Clicking the icon should open the list of roles to switch to. The opened list is empty. The second click opens the complete list as it shoud be.

**Screenshots**
above in reproduction steps

**Environment**
 - OS: MacOS 13.5.2 and Windows 11
 - Browser Firefox
 - Extension Version 4.0.2 (but the bug is not new)

**Comment by tilfin** [comment]
@kstudzinski Please try the following steps:

1. Open `about:addons` (Manage Your Extensions)
2. Select **AWS Extend Switch Roles**
3. Select **Permissions**
4. Turn on the domains you use in **Optional permissions for added functionality**.

**Comment by kstudzinski** [comment]
Hi, Yes it helped. Thank You for prompt solution!

![image](https://github.com/tilfinltd/aws-extend-switch-roles/assets/13691284/a27507fc-bd53-4285-a97d-e9a5d7de3771)
