### ISSUE TITLE
needs two tries in firefox

### ISSUE THREAD

**Issue by Toretu** [tilfinltd/aws-extend-switch-roles#336]
**Describe the bug**

**To Reproduce**
1. In Firefox (latest) I am in an aws ec2 or any other service. 
2. Click on the aws-extend-switch-role icon

**Expected behavior**
The list of aliases

**Screenshots**
![image](https://github.com/tilfinltd/aws-extend-switch-roles/assets/25929492/19521977-3a8c-4633-9210-b666d1123776)

**Environment**
 - Windows 10
 - Firefox 120

**Additional context**
If i click again on the icon the list is there.,... the behavior is consistent

**Comment by tilfin** [comment]
See #330
